name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: pennsignals/publish_docker-compose@v0.1.0
      - name: publish
        run: docker-compose up -d